version: '3.4'

services:
# Define confituration services 
  rabbitmq:
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  restusers:
    container_name: rest1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - QueueName=eventqueue
    ports:
      - 5102:80
      - 5103:443
      
  restposts:
    container_name: rest2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - QueueName=eventqueue
    ports:
      - 5104:80
      - 5105:443

  postgredb:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: userPass
    ports:
      - 5432:5432
