version: '3.4'

services:
# Define confituration services 
  rabbitmq:
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - eventdrivendesign

  restusers:
    container_name: rest1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - QueueName=eventqueue
      - HostDB=postgres
    ports:
      - 5102:80
      - 5103:443
    networks:
      - eventdrivendesign
      
  restposts:
    container_name: rest2
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - QueueName=eventqueue
      - HostDB=postgres
    ports:
      - 5104:80
      - 5105:443
    networks:
      - eventdrivendesign

  postgredb:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: userPass
    ports:
      - 5432:5432
    networks:
      - eventdrivendesign
    volumes:
      - eventdrivendesign-sqldata:/var/lib/postgresql/data \

networks:
  eventdrivendesign:
    driver: bridge

volumes:
  eventdrivendesign-sqldata:
    external: false